name: build

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - stable/**

jobs:
  image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - uses: vexxhost/docker-atmosphere/.github/actions/checkout@2023.1
        with:
          repository: openstack/octavia
          ref: ba397f07a7331190208c93368ee23826ac4e2707

      - uses: vexxhost/docker-atmosphere/.github/actions/checkout@2023.1
        with:
          repository: openstack/ovn-octavia-provider
          ref: 2564f92911840664df8a424697e7c7c8dd9c9865

      - uses: vexxhost/docker-atmosphere/.github/actions/build-image@2023.1
        with:
          image-name: octavia
          build-contexts: |
            octavia=openstack/octavia
            ovn-octavia-provider=openstack/ovn-octavia-provider
          push: ${{ github.event_name != 'pull_request' }}
